profiles:
  frontend:
    windows:
      - name: editor
        commands:
          - "send-keys -t {{.Session}}:{{.Window}} 'nvim' Enter"
      - name: runtime 
        commands:
          - "send-keys -t {{.Session}}:{{.Window}} 'pnpm dev' Enter"
